Repository Stitch07/godfather, pull requests merged in 2021-01, with the labels that each got.

#62 Crusader
  src/lib/mafia/managers/NightActionsManager.ts
  src/lib/mafia/roles/town/Bodyguard.ts
  src/lib/mafia/roles/town/Crusader.ts
Labels: Meta: Roles, SEM: Minor, Status: Needs Testing

#66 refactor: remove all usages of the word lynch
  src/assets/roledocs.json
  src/commands/Mafia/noelim.ts
  src/commands/Mafia/unvote.ts
  src/commands/Mafia/vote.ts
  src/lib/mafia/Game.ts
  src/lib/mafia/Role.ts
  src/lib/mafia/factions/Town.ts
  src/lib/mafia/factions/neutral/Executioner.ts
  src/lib/mafia/factions/neutral/Jester.ts
  src/lib/mafia/managers/VoteManager.ts
  src/lib/mafia/roles/neutral/Executioner.ts
  src/lib/mafia/roles/neutral/Jester.ts
  src/lib/mafia/roles/town/Super_Saint.ts
  src/lib/util/utils.ts
  tests/game.test.ts
Labels: Meta: Refactor

#64 feat: add plurality votes
  src/lib/constants.ts
  src/lib/mafia/structures/Game.ts
  src/lib/orm/entities/GuildSettings.ts
  src/lib/orm/migrations/1611297439144-AddPluralityVoting.ts
Labels: Meta: Feature

#75 feat: send message in all games when bot is rebooted
  src/commands/System/reboot.ts
Labels: Meta: Feature, Priority: Low
